import streamlit as st
import pandas as pd
import sqlite3
import re
import requests
import json
import os
import html
import time
import io
import base64
from datetime import datetime
from google import genai
from google.genai import types
from pydantic import BaseModel, Field
from typing import List
from PIL import Image
from gtts import gTTS

# --- EXTRACTOR IMPORTS ---
try:
    from youtube_transcript_api import YouTubeTranscriptApi
    YOUTUBE_API_READY = True
except ImportError:
    YOUTUBE_API_READY = False

try:
    import yt_dlp
    YTDLP_READY = True
except ImportError:
    YTDLP_READY = False

# ====================== CONFIG & DATABASE ======================
st.set_page_config(page_title="Flashcard Pro v6.8", page_icon="🧠", layout="wide")
DB_NAME = "flashcards_v8.db"

def init_db():
    with sqlite3.connect(DB_NAME) as conn:
        c = conn.cursor()
        c.execute('''CREATE TABLE IF NOT EXISTS decks (id INTEGER PRIMARY KEY, name TEXT UNIQUE)''')
        c.execute('''CREATE TABLE IF NOT EXISTS cards (
            id INTEGER PRIMARY KEY, deck_id INTEGER, front TEXT, back TEXT, 
            explanation TEXT, tag TEXT, next_review TEXT, interval INTEGER, ease REAL)''')
        conn.commit()

init_db()

# ====================== COOKIE TRANSLATOR (JSON TO NETSCAPE) ======================

def prepare_cookies():
    """Converts the JSON cookies from Kiwi/Extension into Netscape format for yt-dlp."""
    json_path = "youtube_cookies.json"
    txt_path = "youtube_cookies.txt"
    
    if not os.path.exists(json_path):
        return None

    try:
        with open(json_path, 'r') as f:
            cookies_json = json.load(f)
        
        with open(txt_path, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by the app from youtube_cookies.json\n\n")
            for c in cookies_json:
                domain = c.get('domain', '')
                # Netscape format requires specific tab-separated values
                # Domain, Include Subdomains (Flag), Path, Secure, Expiry, Name, Value
                flag = "TRUE" if domain.startswith('.') else "FALSE"
                path = c.get('path', '/')
                secure = "TRUE" if c.get('secure') else "FALSE"
                # Handle session cookies without expiry
                expiry = int(c.get('expirationDate', 0))
                name = c.get('name', '')
                value = c.get('value', '')
                
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
        return txt_path
    except Exception as e:
        st.error(f"Cookie Processing Error: {e}")
        return None

# ====================== THE "REAL" TRANSCRIPT ENGINE ======================

def get_transcript_v3(video_id):
    """Bypasses blocks using translated Netscape cookies."""
    cookie_file = prepare_cookies()
    
    # Try Stage 1: Official API with Cookies
    if YOUTUBE_API_READY:
        try:
            # youtube_transcript_api handles the .txt file path directly
            loader = YouTubeTranscriptApi.list_transcripts(video_id, cookies=cookie_file)
            transcript = loader.find_transcript(['en', 'en-US', 'id']) # Added 'id' since you are in Jakarta
            text = " ".join([t['text'] for t in transcript.fetch()])
            if len(text.strip()) > 100: return text
        except Exception as e:
            print(f"Stage 1 Error: {e}")

    # Try Stage 2: yt-dlp Bypass
    if YTDLP_READY:
        try:
            ydl_opts = {
                'skip_download': True,
                'writesubtitles': True,
                'writeautomaticsub': True,
                'subtitleslangs': ['en', 'id'],
                'quiet': True,
                'cookiefile': cookie_file
            }
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(f"https://www.youtube.com/watch?v={video_id}", download=False)
                # Note: yt-dlp extraction of actual text strings is complex; 
                # usually Stage 1 works once yt-dlp 'pokes' the connection with cookies.
                pass
        except Exception as e:
            print(f"Stage 2 Error: {e}")

    # Stage 3: Proxy Fallback (External)
    try:
        resp = requests.get(f"https://youtubetranscript.com/?server_vid2={video_id}", timeout=10)
        clean_text = html.unescape(re.sub(r'<[^>]+>', ' ', resp.text))
        final = re.sub(r'\s+', ' ', clean_text).strip()
        if len(final) > 100: return final
    except: pass
    
    raise ValueError("YouTube still blocked the request. Try logging in again on Kiwi and refreshing your cookies.")

def extract_vid(url):
    match = re.search(r"(?:v=|\/)([0-9A-Za-z_-]{11})", url)
    return match.group(1) if match else None

# ====================== AI & UI LOGIC ======================

class Flashcard(BaseModel):
    front: str
    back: str
    explanation: str
    tag: str

class FlashcardSet(BaseModel):
    cards: List[Flashcard]

def generate_cards(api_key, text, qty):
    client = genai.Client(api_key=api_key)
    prompt = f"Create {qty} educational flashcards from the provided text. Use <b>bold</b> for key terms. Output JSON."
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=[text],
        config=types.GenerateContentConfig(
            system_instruction=prompt,
            response_mime_type="application/json",
            response_schema=FlashcardSet
        )
    )
    return json.loads(response.text).get("cards", [])

def main():
    st.title("🧠 Flashcard Pro v6.8 (Cookie-Enabled)")
    
    if "transcript_content" not in st.session_state:
        st.session_state.transcript_content = ""

    with st.sidebar:
        api_key = st.text_input("Gemini API Key", type="password")
        st.divider()
        if os.path.exists("youtube_cookies.json"):
            st.success("✅ Cookies JSON detected!")
        else:
            st.warning("⚠️ No cookies found. Create 'youtube_cookies.json' to bypass blocks.")

    tab_gen, tab_lib = st.tabs(["Factory", "Library"])

    with tab_gen:
        col1, col2 = st.columns([2, 1])
        
        with col1:
            url = st.text_input("Video URL", placeholder="https://www.youtube.com/watch?v=...")
            
            if st.button("🔍 Fetch Transcript"):
                vid = extract_vid(url)
                if vid:
                    with st.spinner("Injecting cookies & bypassing blocks..."):
                        try:
                            result = get_transcript_v3(vid)
                            st.session_state.transcript_content = result
                            st.success("Transcript loaded successfully!")
                        except Exception as e:
                            st.error(str(e))
                            st.session_state.transcript_content = ""
                else:
                    st.error("Invalid URL format.")

            st.session_state.transcript_content = st.text_area(
                "Source Text:", 
                value=st.session_state.transcript_content, 
                height=350
            )

        with col2:
            st.subheader("Config")
            deck_name = st.text_input("Deck Name", "YouTube Study Set")
            qty = st.number_input("Card Count", 5, 30, 10)
            
            if st.button("🚀 Build Deck", type="primary", use_container_width=True):
                if not api_key:
                    st.error("API Key Required")
                elif len(st.session_state.transcript_content) < 100:
                    st.warning("Transcript is too short or empty.")
                else:
                    with st.spinner("Gemini is analyzing..."):
                        try:
                            cards = generate_cards(api_key, st.session_state.transcript_content, qty)
                            with sqlite3.connect(DB_NAME) as conn:
                                c = conn.cursor()
                                c.execute("INSERT OR IGNORE INTO decks (name) VALUES (?)", (deck_name,))
                                deck_id = c.execute("SELECT id FROM decks WHERE name=?", (deck_name,)).fetchone()[0]
                                for card in cards:
                                    c.execute("INSERT INTO cards (deck_id, front, back, explanation, tag, next_review, interval, ease) VALUES (?,?,?,?,?,?,1,2.5)",
                                              (deck_id, card['front'], card['back'], card['explanation'], card['tag'], datetime.now().date()))
                                conn.commit()
                            st.balloons()
                            st.success(f"Added {len(cards)} cards!")
                        except Exception as e:
                            st.error(f"AI Error: {e}")

    with tab_lib:
        with sqlite3.connect(DB_NAME) as conn:
            decks = pd.read_sql("SELECT * FROM decks", conn)
            if not decks.empty:
                sel = st.selectbox("Select Deck", decks['name'])
                d_id = decks[decks['name'] == sel]['id'].values[0]
                df = pd.read_sql(f"SELECT front, back, tag FROM cards WHERE deck_id={d_id}", conn)
                st.table(df)
            else:
                st.info("Your library is empty.")

if __name__ == "__main__":
    main()
